spring:
  h2:
    console.enabled: true
  datasource:
    generate-unique-name: false
    url: jdbc:h2:mem:users
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
